# Note the order is intentional to avoid multiple passes of the hooks
minimum_pre_commit_version: 4.0.1
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: check-vcs-permalinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: fix-byte-order-marker
  - id: check-merge-conflict
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.6
  hooks:
  - id: clang-format
    types_or: [c++, c, objective-c, objective-c++]
- repo: https://github.com/arenadotio/pre-commit-ocamlformat
  rev: 0439858f79b3bcb49e757278eb1312e212d7dd4f
  hooks:
  - id: ocamlformat
- repo: https://github.com/jevinskie/pre-commit-dune-format-dune-file
  rev: v0.1.10
  hooks:
  - id: dune-format-dune-file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
