open Ctypes

(* This Types_generated module is an instantiation of the Types
	 functor defined in the type_description.ml file. It's generated by
	 a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open Types
  open F

  module Z3_mini_ctx = struct
    include Z3_mini_ctx (* from Types *)

    let mk = foreign "Z3_mini_mk_context" (int @-> returning t)
    let del = foreign "Z3_mini_del_context" (t @-> returning void)
    let check_sat = foreign "Z3_mini_check_sat" (t @-> string @-> returning int)

    let get_model_with_len =
      foreign "Z3_mini_get_model_with_len"
        (t @-> string @-> ptr size_t @-> returning (ptr char))

    let get_model =
      foreign "Z3_mini_get_model" (t @-> string @-> returning string)

    let del_string = foreign "Z3_mini_del_string" (ptr char @-> returning void)
  end
end
