open Ctypes

(* This Types_generated module is an instantiation of the Types
	 functor defined in the type_description.ml file. It's generated by
	 a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open Types
  open F

  module Z3_mini_ctx = struct
    include Z3_mini_ctx (* from Types *)

    let mk = foreign "Z3_mini_mk_context" (bool @-> returning t)
    let del = foreign "Z3_mini_del_context" (t @-> returning void)

    let check_sat =
      foreign "Z3_mini_check_sat" (t @-> string @-> returning lbool)

    let get_model_with_len =
      foreign "Z3_mini_get_model_with_len"
        (t @-> string @-> ptr size_t @-> returning (ptr (const char)))

    let get_model =
      foreign "Z3_mini_get_model" (t @-> string @-> returning string)
  end
end
